package com.willykez.gitsync.data.repository

import com.willykez.gitsync.data.db.dao.SshKeyDao
import com.willykez.gitsync.data.db.entity.SshKeyEntity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.withContext
import org.bouncycastle.crypto.generators.Ed25519KeyPairGenerator
import org.bouncycastle.crypto.params.Ed25519KeyGenerationParameters
import org.bouncycastle.crypto.params.Ed25519PrivateKeyParameters
import org.bouncycastle.crypto.params.Ed25519PublicKeyParameters
import org.bouncycastle.util.io.pem.PemObject
import org.bouncycastle.util.io.pem.PemWriter
import java.io.StringWriter
import java.security.SecureRandom
import java.util.Base64

/**
 * Plain-text view of an SSH key, for use by GitEngine. Only ever lives in memory.
 */
data class DecryptedSshKey(
    val id: Long,
    val name: String,
    val privateKeyPem: String,
    val publicKeyLine: String,
    val passphrase: String,
)

/**
 * Wraps SshKeyDao so the rest of the app never has to think about encryption or the
 * key-generation math — private keys are encrypted right before being written to Room,
 * decrypted right after being read back, same pattern as CredentialRepository.
 */
class SshKeyRepository(private val dao: SshKeyDao) {

    val allKeys: Flow<List<DecryptedSshKey>> =
        dao.getAllFlow().map { list -> list.map { it.toDecrypted() } }

    suspend fun getAll(): List<DecryptedSshKey> = dao.getAll().map { it.toDecrypted() }

    suspend fun getById(id: Long): DecryptedSshKey? = dao.getById(id)?.toDecrypted()

    /** Generates a new Ed25519 keypair (the modern default — short, fast, and what
     * `ssh-keygen -t ed25519` produces) and stores it. Returns the new row's ID. */
    suspend fun generateKey(name: String, comment: String, passphrase: String = ""): Long =
        withContext(Dispatchers.Default) {
            val generator = Ed25519KeyPairGenerator()
            generator.init(Ed25519KeyGenerationParameters(SecureRandom()))
            val keyPair = generator.generateKeyPair()
            val priv = keyPair.private as Ed25519PrivateKeyParameters
            val pub = keyPair.public as Ed25519PublicKeyParameters

            val privatePem = encodeOpenSshEd25519PrivateKey(priv, pub, comment)
            val publicLine = "ssh-ed25519 " +
                Base64.getEncoder().encodeToString(encodeEd25519PublicKeyBlob(pub)) +
                if (comment.isNotBlank()) " $comment" else ""

            val entity = SshKeyEntity(
                name = name,
                privateKeyPem = TokenCrypto.encrypt(privatePem),
                publicKeyLine = publicLine,
                keyType = "ed25519",
                passphrase = if (passphrase.isNotBlank()) TokenCrypto.encrypt(passphrase) else "",
            )
            dao.insert(entity)
        }

    /** Imports a key the user generated elsewhere (e.g. `ssh-keygen`) and pasted in. */
    suspend fun importKey(name: String, privateKeyPem: String, publicKeyLine: String, passphrase: String = ""): Long {
        val entity = SshKeyEntity(
            name = name,
            privateKeyPem = TokenCrypto.encrypt(privateKeyPem.trim()),
            publicKeyLine = publicKeyLine.trim(),
            keyType = if (publicKeyLine.contains("rsa")) "rsa" else "ed25519",
            passphrase = if (passphrase.isNotBlank()) TokenCrypto.encrypt(passphrase) else "",
        )
        return dao.insert(entity)
    }

    suspend fun deleteKey(key: DecryptedSshKey) {
        dao.delete(SshKeyEntity(id = key.id, name = key.name, privateKeyPem = "", publicKeyLine = key.publicKeyLine))
    }

    suspend fun renameKey(id: Long, newName: String) {
        val existing = dao.getById(id) ?: return
        dao.update(existing.copy(name = newName))
    }

    private fun SshKeyEntity.toDecrypted(): DecryptedSshKey = DecryptedSshKey(
        id = id,
        name = name,
        privateKeyPem = try { TokenCrypto.decrypt(privateKeyPem) } catch (e: Exception) { "" },
        publicKeyLine = publicKeyLine,
        passphrase = if (passphrase.isBlank()) "" else try { TokenCrypto.decrypt(passphrase) } catch (e: Exception) { "" },
    )
}

// ── OpenSSH private key encoding ────────────────────────────────────────────────────
// Hand-rolled because Bouncy Castle (pulled in transitively via the jgit ssh/gpg deps)
// gives us the raw Ed25519 key material but not a ready-made "openssh-key-v1" PEM writer.
// This follows the format documented in PROTOCOL.key from the OpenSSH source tree —
// the same format `ssh-keygen -t ed25519` produces, so keys written here are readable
// by any standard SSH client/server, and keys generated by `ssh-keygen` can be pasted
// in via importKey() above without any conversion.

private const val OPENSSH_MAGIC = "openssh-key-v1\u0000"

private fun encodeEd25519PublicKeyBlob(pub: Ed25519PublicKeyParameters): ByteArray {
    val out = java.io.ByteArrayOutputStream()
    writeSshString(out, "ssh-ed25519".toByteArray(Charsets.US_ASCII))
    writeSshString(out, pub.encoded)
    return out.toByteArray()
}

private fun writeSshString(out: java.io.ByteArrayOutputStream, bytes: ByteArray) {
    val len = bytes.size
    out.write((len ushr 24) and 0xFF); out.write((len ushr 16) and 0xFF)
    out.write((len ushr 8) and 0xFF); out.write(len and 0xFF)
    out.write(bytes)
}

private fun encodeOpenSshEd25519PrivateKey(
    priv: Ed25519PrivateKeyParameters,
    pub: Ed25519PublicKeyParameters,
    comment: String,
): String {
    val pubBlob = encodeEd25519PublicKeyBlob(pub)

    // Unencrypted private section: checkint1, checkint2, keytype, pub, priv||pub, comment, padding
    val privSection = java.io.ByteArrayOutputStream()
    val checkInt = SecureRandom().nextInt()
    fun writeInt(v: Int) {
        privSection.write((v ushr 24) and 0xFF); privSection.write((v ushr 16) and 0xFF)
        privSection.write((v ushr 8) and 0xFF); privSection.write(v and 0xFF)
    }
    writeInt(checkInt); writeInt(checkInt)
    writeSshString(privSection, "ssh-ed25519".toByteArray(Charsets.US_ASCII))
    writeSshString(privSection, pub.encoded)
    // OpenSSH stores the "private key" as seed(32) || pubkey(32) concatenated
    val skAndPk = priv.encoded + pub.encoded
    writeSshString(privSection, skAndPk)
    writeSshString(privSection, comment.toByteArray(Charsets.UTF_8))
    var padByte = 1
    while (privSection.size() % 8 != 0) { privSection.write(padByte); padByte++ }

    val whole = java.io.ByteArrayOutputStream()
    whole.write(OPENSSH_MAGIC.toByteArray(Charsets.US_ASCII))
    writeSshString(whole, "none".toByteArray(Charsets.US_ASCII))     // cipher
    writeSshString(whole, "none".toByteArray(Charsets.US_ASCII))     // kdf
    writeSshString(whole, ByteArray(0))                               // kdf options
    // number of keys
    whole.write(0); whole.write(0); whole.write(0); whole.write(1)
    writeSshString(whole, pubBlob)
    writeSshString(whole, privSection.toByteArray())

    val writer = StringWriter()
    PemWriter(writer).use { it.writeObject(PemObject("OPENSSH PRIVATE KEY", whole.toByteArray())) }
    return writer.toString()
}
